config/routes.rb
Rails.application.routes.draw do

  get 'watches/create/:id' => 'watches#create', as: "watch"

  delete 'watches/destroy/:id' => 'watches#destroy'

  resources :product_attachments
  get 'searches/index'

  get 'bids/new'
  post 'bids/create'


  get 'bids/update'

  get 'bids/edit'

  get 'bids/index'

  get 'bids/show/:id' => 'bids#show', as: "current_bid"
  resources :products do
    get :autocomplete_product_name, on: :collection

  end

  resources :products
#rails g scaffold campaign name:string account:belongs_to
  #
=begin
    :binary
    :boolean
    :date
    :datetime
    :decimal
    :float
    :integer
    :primary_key
    :references
    :string
    :text
    :time
    :timestamp
=end
  devise_for :users
  root to: 'visitors#index'

end

app/models/product_attachment.rb
class ProductAttachment < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/controllers/product_attachments_controller.rb
class ProductAttachmentsController < ApplicationController
  before_action :set_product_attachment, only: [:show, :edit, :update, :destroy]

  # GET /product_attachments
  # GET /product_attachments.json
  def index
    @product_attachments = ProductAttachment.all
  end

  # GET /product_attachments/1
  # GET /product_attachments/1.json
  def show
    respond_to do |f|
      f.js
    end
  end

  # GET /product_attachments/new
  def new
    @product_attachment = ProductAttachment.new
  end

  # GET /product_attachments/1/edit
  def edit
  end

  # POST /product_attachments
  # POST /product_attachments.json
  def create
    @product_attachment = ProductAttachment.new(product_attachment_params)

    respond_to do |format|
      if @product_attachment.save
        format.html { redirect_to @product_attachment, notice: 'Product attachment was successfully created.' }
        format.json { render :show, status: :created, location: @product_attachment }
      else
        format.html { render :new }
        format.json { render json: @product_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_attachments/1
  # PATCH/PUT /product_attachments/1.json
  def update
    respond_to do |format|
      if @product_attachment.update(product_attachment_params)
        format.html { redirect_to @product_attachment, notice: 'Product attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_attachment }
      else
        format.html { render :edit }
        format.json { render json: @product_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_attachments/1
  # DELETE /product_attachments/1.json
  def destroy
    @product_attachment.destroy
    respond_to do |format|
      format.html { redirect_to product_attachments_url, notice: 'Product attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_attachment
      @product_attachment = ProductAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_attachment_params
      params.require(:product_attachment).permit(:product_id, :image)
    end
end

app/helpers/product_attachments_helper.rb
module ProductAttachmentsHelper
end

app/views/product_attachments/_form.html.erb
<%= simple_form_for(@product_attachment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :product_id %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_attachments/_product_attachment.html.erb
<li>
<% if action_name == "show"%>
<%= link_to image_tag(product_attachment.image.medium.url), product_attachment_path(product_attachment), remote:true %>
<% elsif action_name == "index"%>
	<%= link_to image_tag(product_attachment.image.thumb.url), product_attachment_path(product_attachment), remote:true %>
	<% end %>
</li>

<div id="product_images">
</div>

app/views/product_attachments/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @product_attachment.product.name %>
</p>

<span>
	<%=link_to image_tag(@product_attachment.image_url),url_for(:back) %>
</span>

<p>
	<%= link_to 'Edit', edit_product_attachment_path(@product_attachment) %> |
	<%= link_to 'Back', url_for(:back) %>
</p>

app/views/product_attachments/edit.html.erb
<h1>Editing Product Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_attachment %> |
<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_attachments.each do |product_attachment| %>
      <tr>
        <td><%= product_attachment.product_id %></td>
        <td><%= product_attachment.image %></td>
        <td><%= link_to 'Show', product_attachment %></td>
        <td><%= link_to 'Edit', edit_product_attachment_path(product_attachment) %></td>
        <td><%= link_to 'Destroy', product_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product attachment', new_product_attachment_path %>

app/views/product_attachments/new.html.erb
<h1>New Product Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @product_attachment.product.name %>

</p>

<p>
<%=link_to image_tag(@product_attachment.image_url),url_for(:back) %>
</p>

<%= link_to 'Edit', edit_product_attachment_path(@product_attachment) %> |
<%= link_to 'Back', url_for(:back) %>

app/views/product_attachments/show.js.erb
$("#product_images").html("<%= escape_javascript(render('product_attachments/show.html.erb')) %>");