config/routes.rb
Rails.application.routes.draw do

  get 'watches/create/:id' => 'watches#create', as: "watch"

  delete 'watches/destroy/:id' => 'watches#destroy'

  resources :product_attachments
  get 'searches/index'

  get 'bids/new'
  post 'bids/create'


  get 'bids/update'

  get 'bids/edit'

  get 'bids/index'

  get 'bids/show/:id' => 'bids#show', as: "current_bid"
  resources :products do
    get :autocomplete_product_name, on: :collection

  end

  resources :products
#rails g scaffold campaign name:string account:belongs_to
  #
=begin
    :binary
    :boolean
    :date
    :datetime
    :decimal
    :float
    :integer
    :primary_key
    :references
    :string
    :text
    :time
    :timestamp
=end
  devise_for :users
  root to: 'visitors#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, presence:true
  validates :expiration, presence: true
  validates :name, presence:true, length: {in: 3..40}
  #validate :expiration_date_cannot_be_in_the_past
  has_many :product_attachments, dependent: :destroy
  accepts_nested_attributes_for :product_attachments, allow_destroy:true
  scope :expired, ->{where('expiration <= ?', Time.current)}

  belongs_to :user
  has_many :bids
  has_one :line_item, dependent: :destroy
  has_many :watches, dependent: :destroy


  def latest_bid_records(n)
     bids.order(:created_at).last(5)
  end

  def highest_bid
    bids.maximum(:bidded)
  end
  def highest_bid_object
    bids.max_by(&:bidded)
  end


  private
    def expiration_date_cannot_be_in_the_past
      if expiration.present? &&  expiration < Time.current
        errors.add(:expiration, "expiration date must in the future")
      end
    end
    def update_sold_after_expiration
      self.sold = true if expiration <= Time.current
      user = self.user
      max = bids.maximum(:bidded)
      ListItem.new(user_id: user.id,
                   product_id: self.id,
                    quantity: 1,
                    price:max
                  )

    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :user_seller, only: [:new, :edit, :update, :destroy]
  before_action :correct_seller, only: [:edit, :update, :destroy]
  before_action :has_bids, only: [:edit, :update, :destroy]
  autocomplete :product, :name

  # GET /products
  # GET /products.json

  def index
    @products = Product.all
    @bid = Bid.new
    @bidders = []
    unless current_user.nil?
      @watches = current_user.watches
    else
      @watches = []
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @product_attachments = @product.product_attachments
    @bid = Bid.new
    unless current_user.blank?
      @wacthes = current_user.watches
    else
      @watches = []
    end
    unless @product.bids.nil?
      @bidders = Bid.where(product_id: params[:id]).limit(5)
      @highest_bid = @product.bids.maximum(:bidded)
      @number_of_bids = @product.bids.count
      gon.watch.highest_bid = @highest_bid
      gon.watch.number_of_bids = @number_of_bids
    else
      @bidders = []
      @highest_bid = 0
      @number_of_bids = 0
    end
    countdown = set_countdown(@product.expiration)
    time_hash = date_to_hash(countdown)
    gon.time_hash = time_hash
  end

  # GET /products/new
  def new
    @product = Product.new
  end



  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "Product updated"
      redirect_to @product
    else

      render 'edit'
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)
    respond_to do |format|
      if @product.save
        unless params[:product_attachments].blank?
          params[:product_attachments]['image'].each do |i|
            @product_attachments_attributes = @product.product_attachments.create!(image: i)
          end
        end

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def user_seller
       redirect_to root_url unless current_user.seller?
    end
    def correct_seller
      product = Product.find(params[:id])
      redirect_to  root_url unless current_user.id == product.user_id
    end
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:minimum_bid, :maximum_bid,
                                      :description, :name, :expiration,
                                      :category, :user_id,
                                      product_attachments_attributes: [:id, :product_id, :image])
    end
    def has_bids
        @product = Product.find(params[:id])
        redirect_to @product, info: "this product is being bidded on" if has_bids?(@product)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product, html:{multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
		<span class="bids">
		<%= f.input :minimum_bid,class: 'form-control '%>
		</span>
		<span class="bids">
    <%= f.input :maximum_bid, class: 'form-control' %>
		</span>
    <%= f.input :description, class: 'form-control' %>
    <%= f.input :name, class: 'form-control' %>
		<span class="selection">
			<%= f.input :category, collection:["Jewellery",'Misc'], class: 'selection' %>
		</span>
		<%= f.input :expiration,  as: :datepicker%>
  </div>
		<%= f.simple_fields_for :post_attachments do |p| %>
			<div class="form-inputs">
				<%=f.file_field :image, multiple: true, 
				name: "product_attachments[image][]", class: 'btn btn-primary' %>
			</div>
			<% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="row image_container <%= cycle('image_odd', 'image_even') %>"> 
<div class="col-md-4">
	<%unless product.product_attachments.empty?%>
			<%=image_link product.product_attachments[0].image.medium.url, product_path(product)%>
			<% end %>
		</div>
		<div class="col-md-4">
			<h3>
				<%= product.name %>
			</h3>
		</div>
		<div class="col-md-4">
			<h5>
				<%= product.description %>
			</h5>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= render partial: 'shared/index_bid_stats', locals: {product: product} %>
			</div>
			<div class="col-md-4">
			</div>
			<div class="col-md-4">
			</div>
		</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<section class='product_image'>
	<%= render @products %>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<ul class="watches_list"title="currently watching">
					<u>
						<strong>Currently watching</strong>
					</u>
					<%= render partial: @watches %>
				</ul>
			</div>
		</div>
	</div>
</section>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= link_to 'New Product', new_product_path %>
			</div>
		</div>
	</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
	<ul class="product-list">
		<li>
			<h1>
				<%= link_to @product.name, product_path(@product) %>
			</h1>
		</li>
		<li class="photo-box">
			<%# image_tag @product.images %>
				<%= render @product_attachments %>
		</li>
		<li class="product-description">
			 <%= @product.description %>
		</li>
		<li>
				<%= render  'shared/bid_stats', locals: {product: @product} %>
		</li>
		<li>
			<%= link_to 'Edit', edit_product_path(@product) %> |
			<%unless has_bids?(@product)%>
				<%= link_to 'Delete', product_path(@product), method: :delete%> |
				<% end %>
			<%= link_to 'Back', products_path %> | 
			<span class="text-success">
			 <%= link_to 'Watch', watch_path(@product.id) %>
			</span>
		</li>
	</ul>