config/routes.rb
Rails.application.routes.draw do

  get 'watches/create/:id' => 'watches#create', as: "watch"

  delete 'watches/destroy/:id' => 'watches#destroy'

  resources :product_attachments
  get 'searches/index'

  get 'bids/new'
  post 'bids/create'


  get 'bids/update'

  get 'bids/edit'

  get 'bids/index'

  get 'bids/show/:id' => 'bids#show', as: "current_bid"
  resources :products do
    get :autocomplete_product_name, on: :collection

  end

  resources :products
#rails g scaffold campaign name:string account:belongs_to
  #
=begin
    :binary
    :boolean
    :date
    :datetime
    :decimal
    :float
    :integer
    :primary_key
    :references
    :string
    :text
    :time
    :timestamp
=end
  devise_for :users
  root to: 'visitors#index'

end

app/views/layouts/_menu.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<ul class="nav navbar-nav navbar-right">
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to 'Product', products_path %>
			</li>
			<%if user_signed_in? %>
				<li></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown"
					href="#">Account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li></li>
						<li class="divider"></li>
							<li><%=link_to "Log out", destroy_user_session_path, method: "delete"%></li>
					</ul>
				</li>
			<% else %>
				<li><%= link_to "Log in", new_user_session_path %></li>
			<% end %>
			</li>
			<li>
				<%= render 'layouts/search_input' %>

			</li>
		</ul>

		</nav>
	</div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/_search_input.html.erb
<form class="navbar-form " action="<%= searches_index_path %>">
	<div class="form-group has-search" style="display:inline;">
		<div class="input-group">
			<%= autocomplete_field_tag 'search', '', autocomplete_product_name_products_path,
				class:"form-control search-input input-sm col-sm-12 pull-right", placeholder: "Enter in search term..."%>
			<span class="input-group-addon"><span class="glyphicon glyphicon-search form-control-search"></span></span>
		</div>
	</div>
</form>

app/views/layouts/_sidebar.html.erb
<h3>
	placeholder
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<%= include_gon %>
		<title>
			<%= complete_title(yield(:title)) %>
		</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Selloff" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Selloff" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/menu' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%#render 'shared/form_errors' %>
			 <div class="container-fluid">
			 	<div class="row">
					<div class="col-md-6 col-md-offset-3 centered">
						<%#get links to products begin watched %>
						<%= yield %>
					</div>
			 	</div>

			 </div>
    </main>
						<%= debug(params) if Rails.env.development? %>
  </body>
</html>